---
- name: iptables
  yum: 
    name: 
      - pygpgme
      - yum-utils 
      - iptables-services 
    state: present
    update_cache: yes

- name: Start iptables services
  service:
    name: iptables
    state: started
    enabled: yes

- name: Copy crowdsec repo file into place.
  template:
    src: templates/crowdsec_crowdsec.j2
    dest: /etc/yum.repos.d/crowdsec_crowdsec.repo
    owner: root
    group: root
    mode: 0644

- name: install Crowdsec
  yum: 
    name: crowdsec
    state: present
    update_cache: yes

- name: Crowdsec-firewall-bouncer-iptables
  yum: 
    name: crowdsec-firewall-bouncer-iptables 
    state: present
    update_cache: yes
